// angular-project/src/app/components/bulk-data/bulk-data.component.ts
import { Component, OnInit } from '@angular/core';
import data from '../../../assets/data.json';

@Component({
  selector: 'app-bulk-data',
  templateUrl: './bulk-data.component.html',
  styleUrls: ['./bulk-data.component.scss']
})
export class BulkDataComponent implements OnInit {

  public list: any = data;

  constructor() { }

  ngOnInit(): void {
  }

}

<table>
    <thead>
        <tr>
            <td>Id</td>
            <td>First name</td>
            <td>Last name</td>
            <td>Email</td>
        </tr>
    </thead>
    <tbody>
      <tr *ngFor="let row of list">
        <td>{{row.id}}</td>
        <td>{{row.first_name}}</td>
        <td>{{row.last_name}}</td>
        <td>{{row.email}}</td>
      </tr>
    </tbody>
</table>

// vue-project/src/components/BulkData.vue
<template>
<table>
  <thead>
        <tr>
            <td>Id</td>
            <td>First name</td>
            <td>Last name</td>
            <td>Email</td>
        </tr>
    </thead>
    <tbody>
      <tr v-for="row in rows" :key="row.id">
        <td>{{row.id}}</td>
        <td>{{row.first_name}}</td>
        <td>{{row.last_name}}</td>
        <td>{{row.email}}</td>
      </tr>
    </tbody>
</table>
</template>

<script>
import data from './../assets/data.json'

export default {
  name: 'BulkData',
  data(){
    return{
      rows: data
    }
  }
}
</script>

<style></style>
