// react-project/src/Components/Home.js
import React, {Component} from "react";
import {Link} from "react-router-dom";


class Home extends Component {

    render() {
        return (
            <div className="Home">
                <p>React.js project</p>
                <Link to="/lazy-load">
                    <button>Lazy Load</button>
                </Link>
                <Link to="/bulk-data">
                    <button>Bulk Data</button>
                </Link>
                <Link to="/request">
                    <button>Request</button>
                </Link>
            </div>
        );
    }
};

export default Home;

// vue-project/src/components/Home.vue
<template>
<div>
  <p>Vue project</p>
  <router-link to="/lazy-load">
    <button>Lazy Load</button>
  </router-link>
  <router-link to="/bulk-data">
    <button>Bulk Data</button>
  </router-link>
  <router-link to="/request">
    <button>Request</button>
  </router-link>
</div>
</template>

<script>
export default {
  name: 'Home'
}
</script>

<style></style>
