// react-project/src/Components/Request.js
import React, { Component } from "react";

class Request extends Component {

    constructor(props) {
        super(props);
        this.state = {
            data: []
        };
    }

    componentDidMount() {
        this.fetchData();
    }

    fetchData(){
        const address = 'https://jsonplaceholder.typicode.com/photos';
        fetch(address)
            .then(response => response.json())
            .then(data => this.setState({ data: data}))
    }

    renderData = () => {
        const dataItems = this.state.data;
        return  dataItems.map(photo => (
            <tr id={photo.id}>
                <td>{photo.albumId}</td>
                <td>{photo.id}</td>
                <td>{photo.title}</td>
                <td>{photo.url}</td>
                <td>
                    <img src={photo.thumbnailUrl}/>
                </td>
            </tr>
        ));
    };

    render() {
        return (
            <table>
                <thead>
                <tr>
                    <td>Album Id</td>
                    <td>Id</td>
                    <td>Title</td>
                    <td>Url</td>
                    <td>ThumbnailUrl</td>
                </tr>
                </thead>
                <tbody>
                    {this.renderData()}
                </tbody>
            </table>
        );
    }
}


export default Request;

// vue-project/src/components/Request.vue
<template>
<table>
  <thead>
      <tr>
          <td>Album Id</td>
          <td>Id</td>
          <td>Title</td>
          <td>Url</td>
          <td>ThumbnailUrl</td>
      </tr>
  </thead>
  <tbody v-if="photos && photos.length">
    <tr v-for="photo in photos" :key="photo.id">
      <td>{{photo.albumId}}</td>
      <td>{{photo.id}}</td>
      <td>{{photo.title}}</td>
      <td>{{photo.url}}</td>
      <td>
          <img v-bind:src="photo.thumbnailUrl">
      </td>
    </tr>
  </tbody>
</table>
</template>

<script>
import { onMounted, ref } from "vue";

export default {
  name: 'Request',
  setup() {
    const photos = ref(null);

    function fetchData() {
      return fetch('http://jsonplaceholder.typicode.com/photos', {
        method: 'get',
        headers: {
          'content-type': 'application/json'
        }
      })
        .then(res => {
          return res.json();
        })
        .then(json => {
          photos.value = json;
        });
    }

    onMounted(() => {
      fetchData();
    });

    return { photos };
  }
}
</script>

<style></style>
